# Conditional playbook
---
- name: Install NGinx on REDHAT AND DEBIAN OS
  hosts: all
  tasks:

       # use the and command below. both conditions must be true 
    - name: install on Debian
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"
      #when: ansible_os_family != "Debian" and ansible_distribution_version == "16.04" ===> not Debian

       # use the or command below. one condition must be true
    - name: install on Redhat
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "Redhat" or ansible_os_family == "SUSE"


## Install list of packages when 
---
-  name: Install list of Packages
   hosts: all
   vars:
     packages:
       - name: nginx
         required: True
       - name: mysql
         required: True
       - name: apache
         required: False
   taskks:
     - name: Installing '{{ item.name }}' on Debian
       apt:
         name: "{{ item.name}}"
         state: present
       when: "{{ item.required }}" == True
       loop: "{{ packages }}"



#### practice for sunday class
---
- name: Deploying Louis' Youtube
  hosts: all
  become: yes # run in supper user mode
  tasks:
    - name: Install HTTPD Service
      yum:
        name: httpd
        state: present
    - name: Start HTTPD Service
      service:
        name: httpd
        state: started
    - name: check HTTPD Status
      command: service httpd status # run the command to check status
      register: service_output
    - name: Print HTTPD Status
      debug:
        var: service_output.stdout # to print only output of active and running
    - name: copy code to target service
      copy:
        src: index.html
        dest: /var/www/html/
    