---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Provision instance
      ec2:
        aws_access_key: AKIA6M2BBVHIWZPV3QCD
        aws_secret_key: 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
        key_name: my_ssh_key_name
        instance_type: t2.micro
        image: ami-0d1cd67c26f5fca19
        wait: yes
        count: 1
        region: us-west-1



# launch command ==> ansible-playbook -v launch.yml